name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  checks:
    name: Build ${{ matrix.node-version }} @ ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - latest
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
